import Head from "next/head";
import Image from "next/image";
import svg from "../public/svg1.svg";

import {
  FaFacebookSquare,
  FaInstagram,
  FaTwitterSquare,
  FaYoutube,
  FaDragon,
} from "react-icons/fa";

import { GiHamburgerMenu } from "react-icons/gi";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-w-screen-2xl m-auto">
        <section className="bg-[url('../public/bg1.jpg')] bg-no-repeat bg-cover bg-center">
          <nav className="mx-20 ">
            <div className="flex flex-col items-center md:flex md:flex-row lg:flex lg:flex-row justify-between">
              <input type={"checkbox"} id="check" className="hidden"></input>

              <div className="flex pl-3 pt-3 lg:pt-5">
                <FaDragon className="text-xl text-red-600 mt-2 lg:mt-1 lg:text-3xl " />
                <h2 className="font-bold text-white text-2xl pl-2 lg:text-3xl">
                  APIDURA
                </h2>
              </div>

              <ul className=" float-right mr-10 mb-10  leading-[80px] text-gray-900 font-bold uppercase rounded fixed lg:text-white lg:flex lg:mx-auto lg:relative h-[100vh] lg:h-0 w-[100%] lg:w-fit top-52 lg:top-0 left-[-100%] lg:left-0 transition-all duration-500 ease-in-out lg:transition-none text-center backdrop-blur-sm italic">
                <li className="font-bold text-2xl pt-5 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">ABOUT US</a>
                </li>
                <li className="font-bold text-2xl pt-5 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#">BIKEPACKING</a>
                </li>
                <li className="font-bold text-2xl pt-5 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  <a href="#"> SHOP</a>
                </li>
              </ul>

              <div className="pt-5">
                <table class="border-collapse border-2 border-white w-40">
                  <tbody>
                    <tr>
                      <td class="border border-white font-bold pl-2 text-gray-200">
                        $0.00
                      </td>
                      <td class="border border-white font-bold pl-5 text-gray-200">
                        0 ITEMS
                      </td>
                    </tr>
                  </tbody>
                </table>

                <div className="flex justify-around text-2xl pt-5 gap-2 text-gray-200 lg:text-gray-700">
                  <FaFacebookSquare className=" cursor-pointer hover:scale-150 hover:transition-all duration-300 ease-in-out hover:text-blue-800" />
                  <FaInstagram className=" cursor-pointer hover:scale-150 hover:transition-all duration-300 ease-in-out hover:text-orange-500" />
                  <FaTwitterSquare className=" cursor-pointer hover:scale-150 hover:transition-all duration-300 ease-in-out hover:text-blue-500" />
                  <FaYoutube className=" cursor-pointer hover:scale-150  hover:text-red-600 hover:transition-all duration-300 ease-in-out" />
                </div>
              </div>
              <label
                for="check"
                className="float-right text-white text-3xl leading-[80px] mt-6 lg:hidden"
              >
                <GiHamburgerMenu />
              </label>
            </div>
          </nav>

          <div className="mx-auto text-center pt-60 lg:pt-80">
            <h3 className="font-bold text-white text-xl lg:text-3xl">
              LEADING THE EVOLUTION IN
            </h3>
            <h1 className="font-bold text-white text-2xl py-5 lg:text-7xl">
              ULTRALIGHT CYCLING
            </h1>
            <button className="font-semibold text-white ring-4 ring-inset rounded-xl ring-gray-200 py-2 px-5 mt-5 hover:scale-125 transition duration-300 ease-in-out ">
              VIEW PRODUCTS
            </button>

            <div className="w-full h-40 mt-52 lg:h-40 lg:mt-52 bg-gradient-to-b from-transparent to-gray-500 text-transparent">
              s
            </div>
          </div>
        </section>

        <section>
          <div className=" bg-gray-500 py-40">
            <div className=" flex flex-col mx-auto lg:flex lg:flex-row lg:justify-center">
              <div className="bg-[url('../public/bc2.jpg')] bg-no-repeat bg-cover bg-center w-72 h-72 lg:w-80 lg:h-80 shadow-2xl shadow-orange-400 rounded-3xl mt-10 mx-auto lg:mx-10 cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
                <div className="mx-20 text-center mt-40 lg:mt-48 backdrop-blur-sm">
                  <h3 className="font-semibold text-white text-xl">
                    AMBASSADORS
                  </h3>

                  <button className="font-semibold text-white ring-4 ring-inset rounded-xl ring-gray-200 py-2 px-5 mt-3 hover:scale-125 transition duration-300 ease-in-out ">
                    LEARN MORE
                  </button>
                </div>
              </div>

              <div className="bg-[url('../public/bag1.jpg')] bg-no-repeat bg-cover bg-center w-72 h-72 lg:w-80 lg:h-80 bg-white shadow-2xl shadow-orange-400 rounded-3xl mt-10 mx-auto lg:mx-10 cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
                <div className="mx-20 text-center mt-40 lg:mt-48 backdrop-blur-sm">
                  <h3 className="font-semibold text-white text-xl">SHOP</h3>
                  <button className="font-semibold text-white ring-4 ring-inset rounded-xl ring-gray-200 py-2 px-5 mt-3 hover:scale-125 transition duration-300 ease-in-out ">
                    LEARN MORE
                  </button>
                </div>
              </div>
            </div>

            <div className="flex flex-col mx-auto lg:flex lg:flex-row lg:justify-center">
              <div className="bg-[url('../public/mont2.jpg')] bg-no-repeat bg-cover bg-center w-72 h-72 lg:w-80 lg:h-80 bg-white shadow-2xl shadow-blue-400  rounded-3xl mt-10 mx-auto lg:mx-10 cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
                <div className="mx-20 text-center mt-40 lg:mt-48 backdrop-blur-sm">
                  <h3 className="font-semibold text-white text-xl">
                    ADVENTURES
                  </h3>
                  <button className="font-semibold text-white ring-4 ring-inset rounded-xl ring-gray-200 py-2 px-5 mt-3 hover:scale-125 transition duration-300 ease-in-out ">
                    LEARN MORE
                  </button>
                </div>
              </div>

              <div className="bg-[url('../public/stuff1.jpeg')] bg-no-repeat bg-cover bg-center w-72 h-72 lg:w-80 lg:h-80 bg-white shadow-2xl shadow-blue-400 rounded-3xl mt-10 mx-auto lg:mx-10 cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
                <div className="mx-20 text-center mt-32 lg:mt-48 backdrop-blur-sm">
                  <h3 className="font-semibold text-white text-xl">
                    MATERIALS & DESIGN
                  </h3>
                  <button className="font-semibold text-white ring-4 ring-inset rounded-xl ring-gray-200 py-2 px-5 mt-3 hover:scale-125 transition duration-300 ease-in-out ">
                    LEARN MORE
                  </button>
                </div>
              </div>

              <div
                className="bg-[url('../public/bc3.jpg')] bg-no-repeat bg-cover bg-center w-72 h-72 lg:w-80 lg:h-80 bg-white shadow-2xl shadow-blue-400
               rounded-3xl mt-10 mx-auto lg:mx-10 cursor-pointer hover:scale-110 transition duration-300 ease-in-out"
              >
                <div className="mx-20 text-center mt-32 lg:mt-48 backdrop-blur-sm">
                  <h3 className="font-semibold text-white text-xl">
                    SPECIAL FEATURES
                  </h3>
                  <button className="font-semibold text-white ring-4 ring-inset rounded-xl ring-gray-200 py-2 px-5 mt-3 hover:scale-125 transition duration-300 ease-in-out ">
                    LEARN MORE
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="bg-[url('../public/bg4.jpg')] bg-no-repeat bg-cover bg-center">
            <div className="w-full h-40 pt-40 bg-gradient-to-t from-transparent to-gray-500 text-transparent">
              s
            </div>
            <hr className="bg-gray-200 my-10 mx-auto w-[50%] h-1 rounded border-0"></hr>

            <div className="mx-3 text-center lg:mx-auto">
              <h3 className=" font-bold  text-white text-xl lg:text-2xl">
                Apidura is driving the evolution in ultralight cycling and
                opening a new world of riding possibilitas for passianate
                cyclists.
              </h3>
            </div>

            <hr className="bg-white mt-10 mx-auto w-[90%] h-1 rounded border-0"></hr>

            <div className="flex flex-col divide-white lg:divide-x-4 lg:flex lg:flex-row">
              <div className="mx-auto py-20 lg:px-10">
                <h3 className="font-bold text-white text-xl lg:text-2xl">
                  ABOUT US
                </h3>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Concept
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Company
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Mountain & Design
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Careers
                </p>
              </div>

              <div className="mx-auto py-20 lg:px-10 ">
                <h3 className="font-bold text-white text-xl lg:text-2xl">
                  BIKEPACKING
                </h3>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Concept
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Company
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Mountain & Design
                </p>
              </div>

              <div className="mx-auto py-20 lg:px-10 ">
                <h3 className="font-bold text-white text-xl lg:text-2xl">
                  SHOP
                </h3>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Concept
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Company
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Mountain & Design
                </p>
              </div>

              <div className="mx-auto py-20 lg:px-10">
                <h3 className="font-bold text-white text-xl lg:text-2xl">
                  CONTACT US
                </h3>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Concept
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Company
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Mountain & Design
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Mountain & Design
                </p>
                <p className=" font-semibold text-white text-xl italic pt-3 cursor-pointer hover:scale-110 hover:transition-all duration-300 ease-in-out">
                  Mountain & Design
                </p>
              </div>

              <div className="mx-auto py-20 lg:px-10">
                <div className="flex flex-col items-center pt-3 lg:pt-5 lg:pl-3">
                  <FaDragon className="text-3xl text-red-600 mt-2 lg:mt-1 lg:text-7xl " />
                  <h2 className="font-bold text-white text-2xl pt-2 pl-2 lg:text-3xl">
                    APIDURA
                  </h2>
                </div>

                <div className="flex justify-around text-2xl pt-5 gap-2 text-white">
                  <FaFacebookSquare className=" cursor-pointer hover:scale-150 hover:transition-all duration-300 ease-in-out hover:text-blue-800" />
                  <FaInstagram className=" cursor-pointer hover:scale-150 hover:transition-all duration-300 ease-in-out hover:text-orange-500" />
                  <FaTwitterSquare className=" cursor-pointer hover:scale-150 hover:transition-all duration-300 ease-in-out hover:text-blue-500" />
                  <FaYoutube className=" cursor-pointer hover:scale-150  hover:text-red-600 hover:transition-all duration-300 ease-in-out" />
                </div>
              </div>
            </div>

            <hr className="bg-white mx-auto w-[90%] h-1 rounded border-0 "></hr>

            <div className="flex flex-col text-center mx-20 pb-10 py-10 lg:flex lg:flex-row lg:justify-between">
              <h4 className="font-semibold text-xl text-white pt-10">
                2022 Apidura All Rights Reserved
              </h4>
              <h4 className="font-semibold text-xl text-white pt-10">
                Site Design by Owen Pretty
              </h4>
              <h4 className="font-semibold text-xl text-white pt-10">
                Teams of Sevices / Privacy Police / Shipping
              </h4>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
